on:
  workflow_call:
    inputs:
      makefile:
        required: true
        type: string
        default: 'Makefile'
      binary:
        required: true
        type: string

jobs:
  compile:
    name: Compile the source code
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Compile code
        run: |
          cd $(dirname ${{ inputs.makefile }})
          make compile
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.binary }}
          path: ./bin/${{ inputs.binary }}
