on:
  workflow_call:
    inputs:
      makefile:
        required: true
        type: string
        default: 'Makefile'

jobs:
  compile:
    name: Compile the source code
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Compile code
        run: |
          cd $(dirname ${{ inputs.makefile }})
          make compile
