on:
  workflow_call:
    inputs:
      makefile:
        required: true
        type: string
        default: 'Makefile'
      src:
        required: true
        type: string
        default: '.'
      unit_tests:
        type: string
        default: 'false'

jobs:
  oclint:
    name: Lint the project source
    runs-on: ubuntu-latest
    container: drakorgaur/oclint:latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Find project
        run: |
          find ${{ inputs.src }} -name '*.c' -o -name '*.cpp' -o -name '*.h' -o -name '*.hpp'
      - name: Run OCLint
        continue-on-error: true
        run: |
          oclint -report-type html -o oclint.html \
            $(find . -name "*.h" -o -name "*.c") -- -c \
            -Wextra \
            -Wall \
            -Wfloat-equal \
            -Wundef \
            -Wshadow \
            -Wpointer-arith \
            -Wstrict-prototypes
      - name: Format OCLint report
        if: always()
        run: |
          if [ -f oclint.html ]; then
            echo report=$(cat oclint.html | sed -e 's/<head>.*<\/head>//g') | sed -e 's/\/__w\/cicd_base\/cicd_base\///g'>> $GITHUB_ENV
          fi
      - name: Checkout
        uses: actions/checkout@v3
      - name: Comment Pull Request
        uses: thollander/actions-comment-pull-request@v1.4.1
        with:
          GITHUB_TOKEN: ${{ github.token }}
          comment_includes: report
          message: |
            # Lint report
            <details><summary>OCLINT</summary> ${{ env.report }} </details>

  unit_tests:
    name: Run unit tests
    if: ${{ inputs.unit_tests == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Run unit tests
        run: |
            cd $(dirname ${{ inputs.makefile }})
            make test
