on:
  workflow_call:
    inputs:
      makefile:
        required: true
        type: string
        default: 'Makefile'
      src:
        required: true
        type: string
        default: '.'
      unit_tests:
        type: string
        default: 'false'

jobs:
  check_for_changes:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check for changes in src
        id: changes
        run: |  
          changes=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }} -- tests src Makefile)
          if [ -z "$changes" ]; then
            echo "::set-output name=changes::false"
          else
            echo "::set-output name=changes::true"
          fi
  oclint:
    name: Lint the project source
    runs-on: ubuntu-latest
    needs: check_for_changes
    if: ${{ needs.check_for_changes.outputs.changes == 'true' }}
    container: drakorgaur/oclint:latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Run OCLint
        continue-on-error: true
        run: |
          oclint -report-type html -o oclint.html \
            $(find ${{ inputs.src }} ./tests -name '*.c' -o -name '*.cpp' -o -name '*.h' -o -name '*.hpp') -- -c \
            -Wextra \
            -Wall \
            -Wfloat-equal \
            -Wundef \
            -Wshadow \
            -Wpointer-arith \
            -Wstrict-prototypes
      - name: Format OCLint report
        if: always()
        run: |
          if [ -f oclint.html ]; then
            echo report=$(cat oclint.html | sed -e 's/<head>.*<\/head>//g') | sed -e 's/\/__w\/cicd_base\/cicd_base\///g'>> $GITHUB_ENV
          fi
      - name: Checkout
        uses: actions/checkout@v3
      - name: Comment Pull Request
        uses: thollander/actions-comment-pull-request@v1.4.1
        with:
          GITHUB_TOKEN: ${{ github.token }}
          comment_includes: report
          message: |
            # Lint report
            <details><summary>OCLINT</summary> ${{ env.report }} </details>

  unit_tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: check_for_changes
    if: ${{ needs.check_for_changes.outputs.changes == 'true' && inputs.unit_tests == 'true' }}
    container: drakorgaur/google_test:latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Copy tests
        run: |
          mkdir -p /unit/tests  
          cp -r tests/* /unit/tests/
      - name: Build unit tests
        run: |
          cd /unit \
          && cmake -S . -B build \
          && cmake --build build
      - name: Run unit tests
        run: |
          cd /unit/build \
          && ctest
