on:
  workflow_call:
    inputs:
      makefile:
        required: true
        type: string
        default: './Makefile'
      binary:
        required: true
        type: string

jobs:
  compile:
    uses: Drakorgaur/cicd_base/.github/workflows/compile.yml@master
    with:
      makefile: ${{ inputs.makefile }}
      binary: ${{ inputs.binary }}
  high_level_tests:
    needs: compile
    uses: Drakorgaur/cicd_base/.github/workflows/high_level_tests.yml@master
    with:
      binary: ${{ inputs.binary }}
  pack:
    needs: high_level_tests
    uses: Drakorgaur/cicd_base/.github/workflows/pack.yml@master
    with:
      makefile: ${{ inputs.makefile }}
      binary: ${{ inputs.binary }}
