on:
  workflow_call:
    inputs:
      makefile:
        required: true
        type: string
        default: './Makefile'

jobs:
  compile:
    uses: ./.github/workflows/compile.yml
    with:
      makefile: ${{ inputs.makefile }}
  high_level_tests:
    needs: compile
    uses: ./.github/workflows/high_level_tests.yml
  pack:
    needs: high_level_tests
    uses: ./.github/workflows/pack.yml
    with:
      makefile: ${{ inputs.makefile }}
