on:
  workflow_call:
    inputs:
      makefile:
        required: true
        type: string
        default: './Makefile'
      src:
        required: true
        type: string
        default: '.'
      unit_tests:
        type: string
        default: 'false'

jobs:
  low_level_tests:
    uses: Drakorgaur/cicd_base/.github/workflows/low_level_tests.yml@master
    with:
      src: ${{ inputs.src }}
      unit_tests: ${{ inputs.unit_tests }}
      makefile: ${{ inputs.makefile }}